version: '3'
services:
    node:
        build: .
        container_name: basics-node-js
        ports:
            - ${PORT}:${PORT}
        depends_on:
            - postgres
        environment:
            - PORT=${PORT}
        restart: always
        volumes:
            - logs:/opt/app/logs
        networks:
            - my-net
    postgres:
        build: ./database/
        container_name: basics-postgres
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        restart: always
        volumes: 
            - postgres_data:/var/lib/postgresql/data
            - postgres_logs:/logs:z
        networks:
            - my-net

networks:
    my-net:
        driver: bridge

volumes:
    logs:
    postgres_data:
    postgres_logs: